### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'GetGeometryType'

### ISSUE THREAD

**Issue by scvetkovski** [bjornd/jvectormap#344]
Hi,

Before asking for help, I was searching for this particular error I am getting now, and unlucky there is no answer. 

So I have some .json file with the following configuration:

{
  "input_file": "/home/stefan/Desktop/jvectormap/RESOURCE/SSC_2011_AUST.shp",
  "output_file": "jquery-jvectormap-aust-en.js",
  "name_field": "SSC_NAME",
  "code_field": "SSC_CODE",
  "longitude0": 11.5,
  "name": "australia",
  "input_file_encoding":"UTF-8",
  "projection": "mill"
}

I am executing: python converter.py australia.json and I am getting the following output

Generating jquery-jvectormap-aust-en.js
Traceback (most recent call last):
  File "converter.py", line 299, in <module>
    converter.convert(paramsJson['output_file'])
  File "converter.py", line 170, in convert
    self.loadData()
  File "converter.py", line 107, in loadData
    self.loadDataSource( sourceConfig )
  File "converter.py", line 139, in loadDataSource
    geometryType = geometry.GetGeometryType()
AttributeError: 'NoneType' object has no attribute 'GetGeometryType'

So where I am doing wrong ?

**For more informations about the SSC_2011_AUST.shp file.
http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1270.0.55.003Explanatory%20Notes10July%202011?OpenDocument

**Comment by scvetkovski** [comment]
Issue closed - reason: outdated.
